### ISSUE TITLE
Make manifesto.json

### ISSUE THREAD

**Issue by nao-pon** [johnfort/elFinder.themes#1]
@johnfort It is a wonderful theme! 👍 Can you create manifesto.json so that it can be set easily with elFinder?

If possible, I think that it should be created in gh-pages.

For example ...

```json
{
   "name":"Theme by JohnFort",
   "cssurls":"https://cdn.jsdelivr.net/gh/johnfort/elFinder.themes/css/elfinder.theme.min.css",
   "author":"JohnFort",
   "email":"",
   "license":"",
   "link":"https://github.com/johnfort/elFinder.themes",
   "image":"https://raw.githubusercontent.com/johnfort/elFinder.themes/master/Screenshorts/Main-view-icons.png",
   "description":""
}
```

Also, after version release you will be able to specify the version at [jsdelivr.net](https://www.jsdelivr.com/?docs=gh).

**Comment by johnfort** [comment]
@nao-pon manifest is done. Check heights navbar & cwd-table after change theme. I have problem with it (see horiz scrolls).

**Comment by nao-pon** [comment]
The link to "img" seems to be broken in "cdn/dark - slim.min.css" defined in the manifesto.

Please check with elFinder client config...
```javascript
themes : {
    'Dark Slim': 'https://cdn.jsdelivr.net/gh/johnfort/elFinder.themes/dark-slim/manifest.json'
}
```

**Comment by nao-pon** [comment]
And, It seems that there is no problem with the navbar's height and horizontal scrolling.

**Comment by nao-pon** [comment]
I think that url is a relative path.

e.g. `url(../dark-slim/img/elfinder.woff2)`

Github's `raw` does not send the appropriate MIME-Type. You need to use CDN such as gh-pages or. jsdelivr.net.

**Comment by johnfort** [comment]
@nao-pon relative path - done =) (& remove cdn dir)
CDN service cached crs's for long time...(

> The link to "img" seems to be broken in "cdn/dark - slim.min.css" defined in the manifesto.

Where problem ? I don't understand
see new manifest, but is it cached in cdn

**Comment by nao-pon** [comment]
@johnfort You can specify the version using "@" on jsdelivr.net.

e.g. https://cdn.jsdelivr.net/gh/johnfort/elFinder.themes@308bd5fa2a90a3d95ac8b8d27492d4a2cffcc730/dark-slim/manifest.json

However, usability is poor as a URL to be released to a third party as manifesto. I recommend putting manifesto.js in gh-pages. The response of gh-pages is slower than cdn.jsdelivr.net, but the cache is updated every time you commit. It also outputs the appropriate MIME-Type and "Access-Control-Allow-Origin" header.

>> The link to "img" seems to be broken in "cdn/dark - slim.min.css" defined in the manifesto.
>
>Where problem ? I don't understand

It was not a "broken link" but a problem with the "Access-Control-Allow-Origin" header. This problem was solved by using relative path. Thanks!
